// Dump DDL produksi sewara via Supabase Management API (baca pg_catalog).
// Run: node dump_schema_prod.mjs
import fs from 'node:fs';

const PAT = fs.readFileSync('E:/Aplikasi Inventory/token dump.txt', 'utf8').trim();
const REF = 'obhvrzholszhjnpvmnna';
const URL = `https://api.supabase.com/v1/projects/${REF}/database/query`;
const OUT = 'E:/Aplikasi Inventory/sewara-split/sewara-backend/supabase/schema_prod_20260930.sql';

async function rows(sql) {
  const r = await fetch(URL, {
    method: 'POST',
    headers: { authorization: `Bearer ${PAT}`, 'content-type': 'application/json' },
    body: JSON.stringify({ query: sql }),
  });
  if (!r.ok) throw new Error(`HTTP ${r.status}: ${(await r.text()).slice(0, 300)}`);
  const j = await r.json();
  if (!Array.isArray(j)) throw new Error(JSON.stringify(j).slice(0, 300));
  return j;
}

const SECTIONS = [
  ['extensions', `SELECT 'CREATE EXTENSION IF NOT EXISTS '||quote_ident(e.extname) ddl
   FROM pg_extension e JOIN pg_namespace n ON n.oid=e.extnamespace
   WHERE e.extname NOT IN ('plpgsql','pgcrypto','uuid-ossp','pg_stat_statements','supabase_vault')
     AND n.nspname NOT IN ('pg_catalog','information_schema') ORDER BY e.extname`],
  ['enums', `SELECT 'CREATE TYPE public.'||quote_ident(t.typname)||' AS ENUM ('||string_agg(quote_literal(e.enumlabel),', ' ORDER BY e.enumsortorder)||')' ddl
   FROM pg_type t JOIN pg_enum e ON e.enumtypid=t.oid JOIN pg_namespace n ON n.oid=t.typnamespace
   WHERE n.nspname='public' GROUP BY t.typname ORDER BY t.typname`],
  ['sequences (non-identity)', `SELECT 'CREATE SEQUENCE public.'||quote_ident(c.relname) ddl FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
   WHERE c.relkind='S' AND n.nspname='public'
     AND NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.objid=c.oid AND d.deptype='i')
   ORDER BY c.relname`],
  ['tables', `SELECT 'CREATE TABLE public.'||quote_ident(c.relname)||' ('||E'\\n  '||string_agg(
      '    '||quote_ident(a.attname)||' '||format_type(a.atttypid,a.atttypmod)||
      CASE WHEN a.attidentity='a' THEN ' GENERATED ALWAYS AS IDENTITY' WHEN a.attidentity='d' THEN ' GENERATED BY DEFAULT AS IDENTITY' ELSE '' END||
      CASE WHEN a.attgenerated='s' THEN ' GENERATED ALWAYS AS ('||pg_get_expr(d.adbin,d.adrelid)||') STORED' ELSE '' END||
      CASE WHEN a.attnotnull AND a.attidentity='' AND a.attgenerated='' THEN ' NOT NULL' ELSE '' END||
      CASE WHEN d.adbin IS NOT NULL AND a.attidentity='' AND a.attgenerated='' THEN ' DEFAULT '||pg_get_expr(d.adbin,d.adrelid) ELSE '' END,
      E',\\n  ' ORDER BY a.attnum)||E'\\n)' ddl
   FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
   LEFT JOIN pg_attribute a ON a.attrelid=c.oid AND a.attnum>0 AND NOT a.attisdropped
   LEFT JOIN pg_attrdef d ON d.adrelid=c.oid AND d.adnum=a.attnum
   WHERE c.relkind='r' AND n.nspname='public' GROUP BY c.oid, c.relname ORDER BY c.relname`],
  ['indexes', `SELECT pg_get_indexdef(i.indexrelid) ddl FROM pg_index i JOIN pg_class c ON c.oid=i.indrelid JOIN pg_namespace n ON n.oid=c.relnamespace
   WHERE n.nspname='public' AND NOT EXISTS (SELECT 1 FROM pg_constraint co WHERE co.conindid=i.indexrelid AND co.conrelid=i.indrelid)
   ORDER BY c.relname, i.indexrelid::regclass::text`],
  ['constraints', `SELECT 'ALTER TABLE public.'||quote_ident(cls.relname)||' ADD CONSTRAINT '||quote_ident(con.conname)||' '||pg_get_constraintdef(con.oid) ddl
   FROM pg_constraint con JOIN pg_class cls ON cls.oid=con.conrelid JOIN pg_namespace n ON n.oid=cls.relnamespace
   WHERE n.nspname='public' AND con.contype<>'t'
   ORDER BY CASE con.contype WHEN 'p' THEN 0 WHEN 'u' THEN 1 WHEN 'c' THEN 2 ELSE 3 END, cls.relname, con.conname`],
  ['views', `SELECT 'CREATE OR REPLACE VIEW public.'||quote_ident(c.relname)||' AS '||pg_get_viewdef(c.oid,true) ddl
   FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE c.relkind='v' AND n.nspname='public' ORDER BY c.relname`],
  ['replica identity (non-default)', `SELECT 'ALTER TABLE public.'||quote_ident(c.relname)||' REPLICA IDENTITY '||CASE c.relreplident WHEN 'f' THEN 'FULL' WHEN 'n' THEN 'NOTHING' WHEN 'i' THEN 'USING INDEX' ELSE 'DEFAULT' END ddl
   FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE c.relkind='r' AND n.nspname='public' AND c.relreplident <> 'd' ORDER BY c.relname`],
  ['functions', `SELECT pg_get_functiondef(p.oid) ddl FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
   WHERE n.nspname='public' ORDER BY p.proname`],
  ['triggers', `SELECT pg_get_triggerdef(t.oid) ddl FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace
   WHERE NOT t.tgisinternal AND n.nspname='public' ORDER BY c.relname, t.tgname`],
  ['policies', `SELECT 'CREATE POLICY '||quote_ident(pol.polname)||' ON public.'||quote_ident(c.relname)||
     ' AS '||CASE pol.polpermissive WHEN true THEN 'PERMISSIVE' ELSE 'RESTRICTIVE' END||
     ' FOR '||CASE pol.polcmd WHEN 'r' THEN 'SELECT' WHEN 'a' THEN 'INSERT' WHEN 'w' THEN 'UPDATE' WHEN 'd' THEN 'DELETE' ELSE 'ALL' END||
     ' TO '||COALESCE(NULLIF((SELECT string_agg(r.rolname,', ') FROM pg_roles r WHERE r.oid = ANY(pol.polroles)),''),'PUBLIC')||
     CASE WHEN pol.polqual IS NOT NULL THEN ' USING ('||pg_get_expr(pol.polqual,pol.polrelid)||')' ELSE '' END||
     CASE WHEN pol.polwithcheck IS NOT NULL THEN ' WITH CHECK ('||pg_get_expr(pol.polwithcheck,pol.polrelid)||')' ELSE '' END ddl
   FROM pg_policy pol JOIN pg_class c ON c.oid=pol.polrelid JOIN pg_namespace n ON n.oid=c.relnamespace
   WHERE n.nspname='public' ORDER BY c.relname, pol.polname`],
  ['rls enable', `SELECT 'ALTER TABLE public.'||quote_ident(c.relname)||' ENABLE ROW LEVEL SECURITY' ddl
   FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE c.relrowsecurity AND n.nspname='public' ORDER BY c.relname`],
  ['rls force', `SELECT 'ALTER TABLE public.'||quote_ident(c.relname)||' FORCE ROW LEVEL SECURITY' ddl
   FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE c.relforcerowsecurity AND n.nspname='public' ORDER BY c.relname`],
  ['comments', `SELECT 'COMMENT ON TABLE public.'||quote_ident(c.relname)||' IS '||quote_literal(d.description) ddl
   FROM pg_description d JOIN pg_class c ON c.oid=d.objoid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE d.objsubid=0 AND n.nspname='public'
   UNION ALL
   SELECT 'COMMENT ON COLUMN public.'||quote_ident(c.relname)||'.'||quote_ident(a.attname)||' IS '||quote_literal(d.description) ddl
   FROM pg_description d JOIN pg_class c ON c.oid=d.objoid JOIN pg_namespace n ON n.oid=c.relnamespace
   JOIN pg_attribute a ON a.attrelid=c.oid AND a.attnum=d.objsubid WHERE d.objsubid>0 AND n.nspname='public'`],
  ['sequence sync', `SELECT 'SELECT setval('||quote_literal(s.schemaname||'.'||s.sequencename)||', '||s.last_value||', true)' ddl
   FROM pg_sequences s WHERE s.schemaname='public' AND s.last_value IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.objid=(quote_ident(s.schemaname)||'.'||quote_ident(s.sequencename))::regclass AND d.deptype='i')
   ORDER BY s.sequencename`],
];

const header = `-- DDL produksi sewara (project ${REF}) — direkonstruksi dari pg_catalog via Management API
-- Tanggal: 2026-09-30. Skema: public saja. TANPA data, TANPA grants.
-- Extensions non-default di-emit lebih dulu (pg_net dkk); default Supabase
-- (pgcrypto/uuid-ossp/pg_stat_statements/vault/plpgsql) sudah ada di project baru.
-- File ini = seed DB dev/staging. BUKAN migration untuk produksi.
-- Diakui: urutan best-effort; kalau error "function does not exist" di policies, pindahkan
-- bagian 'functions' lebih awal (sudah diurus di generator).

`;

const out = [header];
const summary = [];
for (const [name, sql] of SECTIONS) {
  const rs = await rows(sql);
  out.push(`-- ===== ${name} (${rs.length}) =====`);
  for (const { ddl } of rs) {
    if (!ddl) continue;
    const s = String(ddl).trim();
    out.push(s.endsWith(';') ? s : s + ';');
    out.push('');
  }
  summary.push(`${name}: ${rs.length}`);
}

fs.writeFileSync(OUT, out.join('\n'), 'utf8');

// inventaris untuk audit ledger nanti
const inv = {
  tables: (await rows(`SELECT tablename tbl FROM pg_tables WHERE schemaname='public' ORDER BY 1`)).map(r => r.tbl),
  policies: await rows(`SELECT count(*)::int n FROM pg_policy pol JOIN pg_class c ON c.oid=pol.polrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public'`),
  functions: (await rows(`SELECT proname nm FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' ORDER BY 1`)).map(r => r.nm),
  sequences: (await rows(`SELECT relname nm FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE relkind='S' AND nspname='public' ORDER BY 1`)).map(r => r.nm),
};
fs.writeFileSync(OUT.replace(/\.sql$/, '_inventory.json'), JSON.stringify(inv, null, 1), 'utf8');

console.log('OK ->', OUT);
console.log(summary.join(' | '));
console.log('tables=' + inv.tables.length, 'functions=' + inv.functions.length, 'sequences=' + inv.sequences.length, 'policies=' + JSON.stringify(inv.policies));
